### ISSUE TITLE
[web] Loading spinner never disappear on Microsoft Edge

### ISSUE THREAD

**Issue by Daztane** [TailorDev/crick#102]
On Microsoft Edge, when we try to navigate to a project page, the loading spinner never disappear.

In the console we can see the following error

> SCRIPT5009: 'URLSearchParams' is undefined
utils.js (5,3)

![loading](https://user-images.githubusercontent.com/3940727/29416677-2c67f16a-8367-11e7-901a-1c4564638ef8.png)

**Comment by willdurand** [comment]
Oh well. I thought we had a polyfill for that. Looks like nope...

**Comment by willdurand** [comment]
Pushed a fix right now, I have confirmed the bug on Edge 14 and fixed it.
