### ISSUE TITLE
[web] Enable remove frames

### ISSUE THREAD

**Issue by renatobenks** [TailorDev/crick#108]
Will be considered remove frames from crick.io?

I'm with this issue, I've trying to sync in local watson local with crick my frames deleted/edited and this not have been updated, how I can do that?

**Comment by jmaupetit** [comment]
Hi @renatobenks ! Thanks for the report. As stated in #107, this is a `watson sync` issue. We definitely need to work on this. Feel free to contribute!

Closing this as duplicate.

**Comment by jmaupetit** [comment]
FYI see: https://github.com/TailorDev/Watson/issues/171
