### ISSUE TITLE
watson deleted frames do not sync with crick

### ISSUE THREAD

**Issue by mr-tabasco** [TailorDev/crick#111]
Just came across watson and crick.io, and giving them a test drive. I've come across a potential problem with keeping crick and watson in sync. I created a few project frames to push to crick, which works fine, but after deleting these frames on my machine I tried syncing and it had no effect on the frames tracked by crick. I also tried deleting the frames manually on crick, but there seems to be no way of doing so.

Are there any plans of supporting such behavior?

Thanks.

**Comment by jmaupetit** [comment]
Hi @mr-tabasco! Thanks for report. This is a Watson issue, that has been discussed here: https://github.com/TailorDev/Watson/issues/171 Unfortunately, we haven't fixed this yet :cry: 

I'll close this issue as duplicate. Do not hesitate to re-open it if you think I made a mistake.
